In [1]:
import datetime

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [4]:
from awesome_puppies import ads_df
from awesome_puppies import votes_df
from awesome_puppies import groupby_agg
from awesome_puppies import regions, region_string

In [3]:
regions()

['boston_region',
 'cedar_rapids_region',
 'cleveland_region',
 'denver_region',
 'las_vegas_region',
 'milwaukee_region',
 'new_york_city_region',
 'philadelphia_region',
 'phoenix_region',
 'raleigh_region',
 'san_francisco_region',
 'tampa_region',
 'washington_dc_region']

In [7]:
?groupby_agg

In [17]:
ads_cand_region = groupby_agg(ads_df, groupby_list=['region_id', 'beneficiary'], func='size', fill_value=0)
ads_cand_region

beneficiary           Clinton  Trump
region_id
boston_region            2701   2196
cedar_rapids_region      3813   1391
cleveland_region         6518   3784
denver_region            1601   3043
las_vegas_region         7864   2939
milwaukee_region         1201   2703
new_york_city_region       42      6
philadelphia_region      8205   4084
phoenix_region           2724    476
raleigh_region           4915   1799
san_francisco_region     6024   3401
tampa_region             7828   4152
washington_dc_region      545   1178

In [13]:
ads_cand_region_norm = groupby_agg(ads_df, groupby_list=['region_id', 'beneficiary'], func='size', fill_value=0)\
.transform(lambda x: x/x.sum(), axis=1)
ads_cand_region_norm

beneficiary            Clinton     Trump
region_id
boston_region         0.551562  0.448438
cedar_rapids_region   0.732706  0.267294
cleveland_region      0.632693  0.367307
denver_region         0.344746  0.655254
las_vegas_region      0.727946  0.272054
milwaukee_region      0.307633  0.692367
new_york_city_region  0.875000  0.125000
philadelphia_region   0.667670  0.332330
phoenix_region        0.851250  0.148750
raleigh_region        0.732052  0.267948
san_francisco_region  0.639151  0.360849
tampa_region          0.653422  0.346578
washington_dc_region  0.316309  0.683691

In [18]:
c = ads_cand_region.T.corr()
c

region_id,boston_region,cedar_rapids_region,cleveland_region,denver_region,las_vegas_region,milwaukee_region,new_york_city_region,philadelphia_region,phoenix_region,raleigh_region,san_francisco_region,tampa_region,washington_dc_region
region_id,,,,,,,,,,,,,
boston_region,1.0,1.0,1.0,-1.0,1.0,-1.0,1.0,1.0,1.0,1.0,1.0,1.0,-1.0
cedar_rapids_region,1.0,1.0,1.0,-1.0,1.0,-1.0,1.0,1.0,1.0,1.0,1.0,1.0,-1.0
cleveland_region,1.0,1.0,1.0,-1.0,1.0,-1.0,1.0,1.0,1.0,1.0,1.0,1.0,-1.0
denver_region,-1.0,-1.0,-1.0,1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,1.0
las_vegas_region,1.0,1.0,1.0,-1.0,1.0,-1.0,1.0,1.0,1.0,1.0,1.0,1.0,-1.0
milwaukee_region,-1.0,-1.0,-1.0,1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,1.0
new_york_city_region,1.0,1.0,1.0,-1.0,1.0,-1.0,1.0,1.0,1.0,1.0,1.0,1.0,-1.0
philadelphia_region,1.0,1.0,1.0,-1.0,1.0,-1.0,1.0,1.0,1.0,1.0,1.0,1.0,-1.0
phoenix_region,1.0,1.0,1.0,-1.0,1.0,-1.0,1.0,1.0,1.0,1.0,1.0,1.0,-1.0
raleigh_region,1.0,1.0,1.0,-1.0,1.0,-1.0,1.0,1.0,1.0,1.0,1.0,1.0,-1.0
san_francisco_region,1.0,1.0,1.0,-1.0,1.0,-1.0,1.0,1.0,1.0,1.0,1.0,1.0,-1.0
tampa_region,1.0,1.0,1.0,-1.0,1.0,-1.0,1.0,1.0,1.0,1.0,1.0,1.0,-1.0
washington_dc_region,-1.0,-1.0,-1.0,1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,1.0